name: my_gasolinera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Se actualiza el SDK para que sea compatible con las últimas versiones de las dependencias.
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Dependencias Actualizadas a las versiones más recientes (Diciembre 2024)
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  

  
  # Database para cache local
  drift: ^2.20.3
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  excel: ^4.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  universal_html: ^2.3.0
  cached_network_image: ^3.4.1
  web: ^1.0.0
  url_launcher: ^6.3.1
  google_maps_cluster_manager_2: ^3.0.0+1
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Se actualiza a la última versión de los lints
  flutter_lints: ^6.0.0
  
  # Code generation para Drift
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4 #Testeo

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/assets/logo.png
    - assets/images/iconoFinal.png
    - assets/images/iconoFavFinal.png
    - assets/images/iconoValencia.png
    - assets/data/